events { worker_connections 1024; }

http {
    # 1. Define the Group of Servers (The "Upstream")
    upstream finledger_backend {
        # These match the service names we will use in docker-compose
        server app1:8080;
        server app2:8080;
    }

    server {
        # 2. Listen on standard Web Port 80
        listen 80;

        location / {
            # 3. Forward traffic to the group defined above
            proxy_pass http://finledger_backend;

            # Pass the original user's IP info to the backend
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
