-- =============================================================================
-- Flyway V1 baseline — the CURRENT schema exactly as Hibernate produced it.
--
-- Derived from a live `pg_dump --schema-only` of a database generated by this
-- application with `spring.jpa.hibernate.ddl-auto=update` (same JPA entities,
-- same Spring Boot physical naming strategy). It is the migration baseline for
-- BOTH cases:
--
--   * Fresh database ........ V1 executes and creates every object below.
--   * Existing database ..... `spring.flyway.baseline-on-migrate=true`
--                             baselines at version 1 and skips V1 because the
--                             objects already exist.
--
-- Physical naming notes (verified from a live dump, do not "normalize"):
--   * @Table(name="ledgerEntries")  -> physical table  `ledger_entries`
--   * Transaction.timestamp is a reserved word and is stored quoted ("timestamp")
--   * Enum check constraints are emitted by Hibernate 6 and are preserved.
--   * UUID PKs carry no DB default; values are generated by the application.
-- =============================================================================

CREATE TABLE accounts (
    account_id   uuid NOT NULL,
    balance      numeric(19,4) NOT NULL,
    created_date timestamp(6) without time zone,
    currency     character varying(255) NOT NULL,
    name         character varying(255) NOT NULL,
    version      bigint,
    user_id      uuid
);

CREATE TABLE ledger_entries (
    ledger_id     uuid NOT NULL,
    amount        numeric(38,2) NOT NULL,
    hash          character varying(255) NOT NULL,
    logged_at     timestamp(6) without time zone,
    previous_hash character varying(255),
    account_id    uuid NOT NULL,
    transaction_id uuid NOT NULL
);

CREATE TABLE roles (
    id        uuid NOT NULL,
    role_name character varying(20) NOT NULL,
    CONSTRAINT roles_role_name_check CHECK (((role_name)::text = ANY
        ((ARRAY['ROLE_ADMIN'::character varying, 'ROLE_USER'::character varying])::text[])))
);

CREATE TABLE transaction (
    transaction_id uuid NOT NULL,
    reference_id   character varying(255) NOT NULL,
    status         character varying(255),
    "timestamp"    timestamp(6) without time zone,
    type           character varying(255),
    CONSTRAINT transaction_status_check CHECK (((status)::text = ANY
        ((ARRAY['PENDING'::character varying, 'PROCESSING'::character varying,
          'COMPLETED'::character varying, 'FAILED'::character varying,
          'REVERSED'::character varying])::text[]))),
    CONSTRAINT transaction_type_check CHECK (((type)::text = ANY
        ((ARRAY['DEPOSIT'::character varying, 'WITHDRAWAL'::character varying,
          'TRANSFER'::character varying, 'REVERSAL'::character varying])::text[])))
);

CREATE TABLE user_role (
    user_id uuid NOT NULL,
    role_id uuid NOT NULL
);

CREATE TABLE users (
    user_id  uuid NOT NULL,
    email    character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    username character varying(255) NOT NULL
);

ALTER TABLE ONLY accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (account_id);
ALTER TABLE ONLY ledger_entries
    ADD CONSTRAINT ledger_entries_pkey PRIMARY KEY (ledger_id);
ALTER TABLE ONLY roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);
ALTER TABLE ONLY transaction
    ADD CONSTRAINT transaction_pkey PRIMARY KEY (transaction_id);
ALTER TABLE ONLY users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);

ALTER TABLE ONLY users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);
ALTER TABLE ONLY accounts
    ADD CONSTRAINT uke4w4av1wrhanry7t6mxt42nou UNIQUE (user_id);
ALTER TABLE ONLY transaction
    ADD CONSTRAINT uki1j1t2ph6hxx6o8e52udym6m1 UNIQUE (reference_id);
ALTER TABLE ONLY users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);

ALTER TABLE ONLY ledger_entries
    ADD CONSTRAINT fkccr7q587j5bf49xqb0fqieefp FOREIGN KEY (account_id)
        REFERENCES accounts(account_id);
ALTER TABLE ONLY ledger_entries
    ADD CONSTRAINT fk1ic55vqevef4qxb31tg90ay7x FOREIGN KEY (transaction_id)
        REFERENCES transaction(transaction_id);
ALTER TABLE ONLY user_role
    ADD CONSTRAINT fkj345gk1bovqvfame88rcx7yyx FOREIGN KEY (user_id)
        REFERENCES users(user_id);
ALTER TABLE ONLY user_role
    ADD CONSTRAINT fkt7e7djp752sqn6w22i6ocqy6q FOREIGN KEY (role_id)
        REFERENCES roles(id);
ALTER TABLE ONLY accounts
    ADD CONSTRAINT fknjuop33mo69pd79ctplkck40n FOREIGN KEY (user_id)
        REFERENCES users(user_id);
